name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - main
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out github code
        uses: actions/checkout@v2

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Run tests   
        run: go test

      - name: Run application for test
        run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: lucasmol/ci-studies:latest
